# Generated by Django 5.0.7 on 2024-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
