# Generated by Django 5.0.7 on 2024-08-06 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adservice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='username',
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
