# Generated by Django 5.0.7 on 2024-08-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adservice', '0002_remove_ad_email_remove_ad_username_ad_price_ad_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
    ]
